[package]
name = "dirkill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dirlib"

[dependencies]
anyhow = "1.0.65"
bytesize = "1.1.0"
clap = { version = "4.0.5", features = ["derive"] }
crossterm = "0.25.0"
dunce = "1.0.2"
fs_extra = "1.2.0"
num-traits = "0.2.15"
parking_lot = "0.12.1"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.15"
tui = "0.19.0"
walkdir = "2.3.2"
