[package]
name = "dirkill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.5", features = ["derive"] }
dunce = "1.0.2"
tui = "0.19.0"
walkdir = "2.3.2"
